### ISSUE TITLE
load the counter animation on first scroll, but not again until page reload

### ISSUE THREAD

**Issue by hipchecker** [ciromattia/jquery.counterup#5]
The counter animation triggers when it's scrolled into view, then if you scroll up and back down again, the animation starts again.

It would be great if by default, or with an option, the animation would only be triggered once no matter how many times you scrolled the element in an out of view.

**Comment by ciromattia** [comment]
It works already like this, check the demo!

**Comment by tonyash** [comment]
no it doesn't, it reloads every time the element comes into the viewport.

**Comment by ciromattia** [comment]
Are you sure? It's an old bug and it should be fixed.
Are you using my fork or @bfintal's? If you got it from bower or npm, make sure you're using *jquery.counterup* and _not_ *jquery-counterup* (with the dot, not the hyphen), because the latter comes from an outdated fork.

**Comment by tonyash** [comment]
My bug report is now over 8 months old. Perhaps a new version fixed it? I ended up implementing a completely different solution because of this bug so I'm no longer in a position to test.

**Comment by alex-edgedesign** [comment]
@ciromattia I came across the same issue myself, i was using version 4.0.1 of waypoints and version 1.0.0 of the jquery.counterup min script from a CDN.

Every time i scrolled down and back up again the counter would half the figure and count up to that figure, then the same would happen again when you scroll up and down again.

The only way i got the original value back that i set is by reloading the page.

What i did to fix this issue, i  changed my waypoints version to match the one on the demo which is version 2.0.3.

Now when i scroll back up and down the page again the counters do not reset anymore so i no longer needs to refresh the page.

To fix this i think you need to remove the triggerOnce option from your JS and replace it with destroy, because waypoints have remove this function by the looks of it.

This is why its probably not working because they might be using the latest version of waypoints.

You can read the issue here for TriggerOnce 
https://github.com/imakewebthings/waypoints/issues/381

Hope this help!

**Comment by lhardie** [comment]
@ciromattia I just downloaded your fork and installed it on a site I'm working on, and it fixed the bug for me... two of them actually. One: it only counts up to the final number once, until I reload the page. Two: It counts to the actual numbers indicated in the HTML even if you scroll and jump around on the page a bunch of times.

Thank you for the fix!
